routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('http://webmail.innsystem.com.br/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });

Route::get('/manutencao', 'Front\HomeController@maintence');
Route::get('/', 'Front\HomeController@suspenso');

Route::get('/sobre', 'Front\AboutController@index');

Route::get('categorias', 'Front\CategoriesController@index');
Route::get('categorias/{slugCategoria}', 'Front\CategoriesController@show');
Route::get('categorias/{slugCategoria}/{slugEstabelecimento}', 'Front\CategoriesController@showEstablishment');

Route::get('calendario/', 'Front\CalendarsController@index');
Route::get('calendario/{slugCalendario}', 'Front\CalendarsController@showCalendar');

Route::get('blogs', 'Front\BlogsController@index');
Route::get('blogs/{slugBlog}', 'Front\BlogsController@show');
Route::get('/depoimentos', 'Front\ReviewController@index');
Route::post('/depoimentos-create', 'Front\ReviewController@store');
Route::get('/contato', 'Front\ContactController@index');

Route::post('/estabelecimentos/busca', 'Front\HomeController@busca');


Route::prefix('services')->namespace('Services')->group(function() {
   Route::post('send-mail', 'MailController@sendContact');
});

Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');

    Route::resource('about', 'Admin\AboutController');
    Route::resource('blogs', 'Admin\BlogsController');
    Route::delete('blogs/{blog}/photos/{photo}', 'Admin\\BlogsController@photoRemove')->name('remove.photo');


    Route::resource('reviews', 'Admin\ReviewsController');
    Route::resource('sliders', 'Admin\SlidersController');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::resource('establishments', 'Admin\EstablishmentsController');
    Route::delete('establishments/{establishment}/photos/{photo}', 'Admin\\EstablishmentsController@photoRemove')->name('remove.photo');

    Route::resource('calendars', 'Admin\CalendarsController');
    Route::delete('calendars/{calendar}/photos/{photo}', 'Admin\\CalendarsController@photoRemove')->name('remove.photo');

    Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    
});

Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    public function establishments()
	{
		return $this->hasMany('Establishment');
	}
    protected $fillable = [
    	'title',
    	'slug',
    	'status',
    	'image'
    ];


    public function photos()
    {
        return $this->hasMany('App\Models\CategoryPhoto'); // espero que tenha compreendido,  sim um aprendizado valioso rs
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\Categories\StoreRequest;
use App\Http\Requests\Admin\Categories\UpdateRequest;

use App\Models\Category;
use App\Models\CategoryPhoto;

use Image;

class CategoriesController extends Controller
{
    /**
     * Armazena uma nova instancia do model Category
     *
     * @var \App\Category
     */
    private $categories;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
      $this->categories = app(Category::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $categories = Category::orderBy($request->input('sort', 'created_at'), 'ASC')->paginate();
      return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
      try {
        app('db')->beginTransaction(); // inicia uma transaçao

        $category = Category::create($request->all()); // nesse momento o registro ja foi criado.
        
        foreach ($request->photos as $photo) {
          $filename = $photo->store("categories/{$category->id}/photos");
            // associa fotos ao category recem criado.
          $category->photos()->create(['filename' => $filename]);
        }

        app('db')->commit(); // confirma transaço

        session()->flash('messages.success', ['Categoria cadastrada com sucesso!']);
        return redirect()->route('categories.index');
      }catch(\Execpetion $error) {
        //
        app('db')->rollback(); // reverte transacao

        session()->flash('messages.error', ['Houve um erro. Tente novamente!']);
        return redirect()->route('categories.index');
      }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $category = Category::findOrFail($id);
      return view('admin.categories.show', compact('category'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $category = Category::findOrFail($id);
      return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreRequest $request, $id)
    {
     $category = $this->categories->where('id', $id)->first();

     if(!$category) {
      session()->flash('messages.error', ['Categoria não existe!']);
      return redirect()->route('categories.index');
    }

      $category->fill($request->all()); // armazena atributos

      $photos = $request->photos; // arquivos

      //
      // Caso exista fotos na ediçao
      //
      if(is_array($photos) && count($photos) > 0) {
        foreach ($photos as $id => $photo) {
          //
          // Verificar se existe foto informada na lista de fotos pertencentes ao category.
          //
          if($category->photos->contains('id', $id)) {
            //
            // registro atual
            //
            $row = $category->photos->find($id);

            $old = $row->filename;

            $row->filename = $photo->store("categories/{$category->id}/photos");

            $row->save(); // atualiza

            if($row->isDirty() && app('filesystem')->exists($old)) {
              app('filesystem')->delete($old);
            }

            continue;
          }
        }
      }

      if($request->hasFile('addPhotos')) {
        //
        // Adicionar novas fotos
        //
        $photos = $request->addPhotos;
        
        foreach ($photos as $file) {
          $filename = $file->store("categories/{$category->id}/photos");
          
          if($filename) {
            //
            // Adicionar foto ao category
            //
            $category->photos()->create(compact('filename'));

            continue;
          }
        }
      }

      $category->save(); // guarda alteraçoes

      session()->flash('messages.success', ['Categoria alterada com sucesso!']);
      return redirect()->route('categories.index');
    }

    public function photoRemove(Category $category, $photo_id)
    {
      //
      // verificar se existe relacionamento
      //
      if(!$category->photos->contains('id', $photo_id)) abort(403, 'Essa imagem não pertence a Categoria.');
      
      $photo = $category->photos->find($photo_id);

      app('db')->beginTransaction();
      
      try {
        $filename = $photo->filename;

        $photo->delete();

        if(app('filesystem')->exists($filename)) {
          // remover do diretorio
          app('filesystem')->delete($filename);
        }

        app('db')->commit();

        return response(null, 204);
      }catch(\Exception $error) {
        app('db')->rollback();
        return response()->json(['message' => $error->getMessage()], 400);
      }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Category $category)
    {

      $category->delete();

      return response(null, 204);
    //return response()->redirectToRoute('categories.index');
    }
  }

app/Http/Controllers/Front/CategoriesController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Establishment;

class CategoriesController extends Controller
{
	 /**
     * Armazena uma nova instancia do model Establishment
     *
     * @var \App\Establishment
     */
	 private $categories;
	 private $establishments;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
    	$this->categories = app(Establishment::class);
    	$this->establishments = app(Establishment::class);
    }

    public function index()
    {
    	return view('front.categories');
    }

    public function show(Category $category)
    {
    	$establishments = Establishment::where('category_id', $category->id)->get();
    	return view('front.categories_show', compact('category', 'establishments'));
    }

    public function showEstablishment(Category $category, Establishment $establishment)
    {
    	$establishment = Establishment::where('category_id', $category->id)->where('id', $establishment->id)->first();
        $establishment->increment('views');
    	return view('front.establishment_show', compact('category', 'establishment'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.base')
@section('title', 'Nova Categoria')

@section('content')
<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('categories.index') }}">Página de Categorias</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            @yield('title')
          </div>

          <div class="panel-body">

            <form action="{{ route('categories.store')}}" enctype="multipart/form-data" method="POST">
              @component('admin.categories.form')
             <div class="row">
              <div class="col-md-12">
                <input type="file" style="display: none;" name="photos[]" id="input-add-photos" multiple>
                <button class="btn btn-success" id="add-photos-to-category" type="button">
                  <i class="fa fa-plus"></i> Selecionar Imagens
                </button>
                <span class="btn disabled" id="display-add-photos">0 selecionados</span>
              </div>
            </div>
            @endcomponent
          </form>

        </div><!-- panel-body -->


      </div><!-- panel-default -->
    </div><!-- col-md-12 -->


  </div><!-- row -->
</div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js?1"></script>

<script>
  /* Adicionar arquivos */
  $('#add-photos-to-category').click(function(e) {
    e.preventDefault();
    $("#input-add-photos").click();
  });

  $("#input-add-photos").change(function(e) {
    let display = $('span#display-add-photos'),
    files = e.target.files,
    count = files.length;

    if(count > 0) {
      display.empty().html(count + ' selecionados.')
    }else{
      display.empty().html('0 selecionados.')
    }
  });
  
  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();

  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="title"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="slug"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.base')
@section('title', 'Editar Categoria')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $category->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('categories.index') }}">Página de Categorias</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End category Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title') - {{ $category->title }}
         </div>

         <div class="panel-body">

          <form action="{{ route('categories.update', $category->id)}}" enctype="multipart/form-data" method="POST">
            <input type="hidden" name="_method" value="PUT">
            @component('admin.categories.form')
                <div id="images" class="tab-pane">

                  <div class="row">
                    <div class="col-md-12">
                      <input type="file" style="display: none;" name="addPhotos[]" id="input-add-photos" multiple>
                      <button class="btn btn-success" id="add-photos-to-category" type="button">
                        <i class="fa fa-plus"></i> Adicionar Imagens
                      </button>
                      <span class="btn disabled" id="display-add-photos">0 selecionados</span>
                    </div>
                  </div>

                  <hr>

                  @slot('category', $category)
                  <div class="row">
                    @forelse($category->photos as $photo)
                    <div id="photo-{{ $photo->id }}" class="col-xs-6 col-sm-4 col-md-3">

                      <div class="panel panel-default">
                        <div class="panel-body">
                          <img id="photo-preview-{{ $photo->id }}" src="{{ asset('storage/' . $photo->filename) }}" alt="{{ $category->slug }}" class="img-thumbnail img-responsive" alt="#{{ $photo->id}}">
                        </div>
                        <div class="panel-footer">
                          <div class="btn-group btn-group-xs">
                            <input type="file" name="photos[{{ $photo->id }}]" id="{{ $photo->id }}" class="update-photo" style="display: none;"/>
                            <button class="btn btn-block btn-info" type="button" onclick="document.getElementById({{ $photo->id }}).click()">Alterar imagem</button>
                            <button class="btn btn-block btn-danger" type="button" onclick="remove({{ $category->id }}, {{ $photo->id }})">Remover</button>
                          </div>
                        </div>
                      </div>
                    </div>
                    @empty
                    <p>Nao existem fotos para essa Categoria.</p>
                    @endforelse
                  </div>                
                </div><!-- tab-images -->
                @endcomponent
          </form>

        </div><!-- panel-body -->


      </div><!-- panel-default -->
    </div><!-- col-md-12 -->


  </div><!-- row -->
</div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js?1"></script>

<script>

  function remove(category, photo) {
    let doc = $('#photo-' + photo);
    let request = $.ajax({
     url: '/dashboard/categorys/' + category + '/photos/' + photo,
     type: 'DELETE',
     statusCode: {
       204: function() {
            doc.fadeOut(); // ocultar registro
          }
        }
      })
  }

  /* Gerar Previa */
  $('.update-photo').change(function(e) {
    console.log('updated.')
    const ref = e.target;

    if(!ref.files) return;

    let id = ref.id,
    image = $('#photo-preview-' + id),
    file = ref.files[0],
    old = image.attr('src')

    var reader = new FileReader();

    reader.onload = function(event) {

      image.css({filter: blur(1.5)})

      image.fadeOut(500, function() {
        image.attr('src', event.target.result);
        image.fadeIn(200, function() {
          image.css({filter: blur(0)})
        });
      })
    }
      //
      reader.readAsDataURL(file);
    });

  /* Adicionar arquivos */
  $('#add-photos-to-category').click(function(e) {
    e.preventDefault();
    $("#input-add-photos").click();
  });

  $("#input-add-photos").change(function(e) {
    let display = $('span#display-add-photos'),
    files = e.target.files,
    count = files.length;

    if(count > 0) {
      display.empty().html(count + ' selecionados.')
    }else{
      display.empty().html('0 selecionados.')
    }
  });


  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();

  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="title"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="slug"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>
@endsection

resources/views/admin/categories/form.blade.php
{!! csrf_field() !!}


{{ $slot }}

<div class="form-group @if ($errors->has('title')) has-error @endif">
  <label for="title" class="form-label">Nome da Categoria</label>
  <input type="text" class="form-control" id="title" name="title" value="{{ $category->title ?? old('title') }}" placeholder="Nome da Categoria" autofocus>
  @if ($errors->has('title'))
  <span class="help-block">
    <strong>{{ $errors->first('title') }}</strong>
  </span>
  @endif
</div><!-- form-group -->


<div class="form-group @if ($errors->has('slug')) has-error @endif">
  <label for="slug" class="form-label">URL Amigável</label>
  <input type="text" class="form-control" id="slug" name="slug" readonly value="{{ $category->slug ?? old('slug') }}" placeholder="URL Amigável">
  <span class="help-block">* É preenchido automaticamente.</span>
  @if ($errors->has('slug'))
  <span class="help-block">
    <strong>{{ $errors->first('slug') }}</strong>
  </span>
  @endif
</div><!-- form-group -->

<div class="form-group @if ($errors->has('status')) has-error @endif">
  <label for="status" class="form-label">Status do Cliente</label>
  <select class="form-control" id="status" name="status">
    @if(isset($category->status))
    @if($category->status == 0 )
    <option value="0" selected>Desabilitado</option> 
    <option value="1">Habilitar</option>
    @else
    <option value="0">Desabilitar</option> 
    <option value="1" selected>Habilitado</option>
    @endif
    @else
    <option value="1" selected>Habilitado</option>
    <option value="0">Desabilitado</option> 
    @endif
  </select>

  @if ($errors->has('status'))
  <span class="help-block">
    <strong>{{ $errors->first('status') }}</strong>
  </span>
  @endif
</div><!-- form-group -->

<div class="row">
  <div class="col-md-6">
    <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-check"></i>Salvar</button>
    <a href="{{ route('categories.index') }}" class="btn btn-sm btn-warning"><i class="fa fa-reply"></i>Cancelar</a>
  </div><!-- col-md-6 -->
</div>

resources/views/admin/categories/index.blade.php
@extends('admin.base')
@section('title', 'Lista de Categorias')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard/') }}">Inicio</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  @include('elements.messages')

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            @yield('title')
          </div>

          <div class="panel-body">
            <div class="table-responsive">
              @if(count($categories) > 0)
              <table class="table table-hover table-bordered table-striped" id="categories-table">
                <thead>
                  <tr>
                    <td width="5%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'id']) }}">#</a></td>
                    <td width="5%">Imagem</td>
                    <td><a href="{{ Request::fullUrlWithQuery(['sort' => 'title']) }}">Title</a></td>
                    <td width="8%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'status']) }}">Status</a></td>
                    <td width="14%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'created_at']) }}">Criação</a></td>
                    <td width="14%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'updated_at']) }}">Alteração</a></td>
                    <td width="15%" class="text-right">Ações</td>
                  </tr>
                </thead>
                <tbody>
                  @foreach($categories as $category)
                  <tr id="row-{{ $category->id }}">
                    <td>
                      <div class="checkbox">
                        <input class="categories" id="checkbox{{ $category->id }}" data-id="{{ $category->id }}" type="checkbox">
                        <label for="checkbox{{ $category->id }}">
                          <b>{{ $category->id }}</b>
                        </label>
                      </div>
                    </td>
                    <td><img src="{{ $category->photos->isNotEmpty() ? asset('storage/' . $category->photos[0]->filename) : ''}}" alt="{{ $category->title }}" class="img-thumbnail"> </td>
                    <td>{{ $category->title }}</td>
                    <td><span class="label label-{{ ($category->status == '1' ? 'success' : 'danger' ) }}">
                      {{ ($category->status == '1' ? 'Habilitado' : 'Desabilitado' ) }}
                    </span>
                    </td>
                    <td>{{ \Carbon\Carbon::parse($category->created_at)->format('d/m/y H:i')  }}</td>
                    <td>{{ \Carbon\Carbon::parse($category->updated_at)->format('d/m/y H:i') }}</td>
                    <td class="text-right">
                      <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-xs btn-primary btn-icon" data-toggle="tooltip" data-original-title="Editar"><i class="fa fa-edit"></i></a>
                      <a href="#" class="btn btn-xs btn-danger btn-icon btn-delete" data-id="{{ $category->id }}" data-toggle="tooltip" data-original-title="Remover"><i class="fa fa-remove"></i></a></li>
                    </td>
                  </tr>
                  @endforeach

                </tbody>
              </table>
              @else
              <div class="alert alert-info">Nenhuma categoria cadastrada.</div>
              @endif
              <hr>

            </div><!-- table-responsive -->
          </div><!-- panel-body -->

          <div class="row">
            <div class="col-md-6">
              <a href="{{ route('categories.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i>Nova Categoria</a>
              <a href="{{ route('establishments.create') }}" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i>Novo Estabelecimento</a>
              <a href="#" class="btn btn-sm btn-danger btn-remove-all"><i class="fa fa-remove"></i>Remover selecionados</a>
            </div><!-- col-md-6 -->

            <div class="col-md-6 text-right">
              {{ $categories->links() }}
            </div><!-- col-md-6 -->
          </div>
          

        </div><!-- panel-default -->
      </div><!-- col-md-12 -->
      

    </div><!-- row -->
  </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection


@section('cssPage')
@endsection

@section('jsPage')
<script>
  $(function() {
    let btn = $('.btn-delete');
    let btnAll = $('.btn-remove-all');

    function remove(id) {
      let tr = $('#categories-table #row-' + id);
      let request = $.ajax({
       url: '/dashboard/categories/' + id,
       type: 'DELETE',
       statusCode: {
         204: function() {
           tr.fadeOut();
         },
         403: function() {
           let copy = tr.innerHTML;

           tr.html('').append('<td colspan="7">Essa categoria não foi removida.</td>')
           .css({'background-color': 'red','color': 'white', 'text-align': 'center'});
         }
       }
     });
      return request;
    }

    btn.on('click', function(e) {
      e.preventDefault();
      let action = $(e.currentTarget);
      let request = remove(action.data('id'));
      request.fail(function() {
        window.alert('Não foi possivel remover a categoria')
      });
    })

    btnAll.on('click', function(e) {
      e.preventDefault();

      let checkbox = $('input:checkbox[class="categories"]:checked');

      if(checkbox.length > 0 && window.confirm('Gostaria de remover a(s) ' + checkbox.length + ' selecionada(s) categoria(s)?')) {
          //
          checkbox.each(function(index, el) {
            let id = $(el).data('id')
            let request = remove(id);
          })
        }

      })
  })
</script>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.base')
@section('title', 'Detalhes da Categoria')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $category->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('categories.index') }}">Página de Categorias</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End category Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            <h2>{{ $category->title }}</h2>
          </div>

          <div class="panel-body">

            <p><small>Criado em {{ $category->created_at->format('d/m/Y H:i:s') }} | Atualizado em {{ $category->updated_at->format('d/m/Y H:i:s') }}</small></p>
            
            <hr>

            <a href="{{ route('categories.index') }}" class="btn btn-xs btn-warning">Voltar</a>
            <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-xs btn-primary">Editar</a>
            <a href="{{ route('categories.destroy', $category->id) }}" class="btn btn-xs btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form-categories').submit();"><i class="fa fa-remove"></i> Deletar</a></li>
            <form id="delete-form-categories" action="{{ route('categories.destroy', $category->id) }}" method="POST" style="display: none;">
             {!! csrf_field() !!}
             <input type="hidden" name="_method" value="DELETE">
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
@endsection