routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('http://webmail.innsystem.com.br/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });

Route::get('/manutencao', 'Front\HomeController@maintence');
Route::get('/', 'Front\HomeController@suspenso');

Route::get('/sobre', 'Front\AboutController@index');

Route::get('categorias', 'Front\CategoriesController@index');
Route::get('categorias/{slugCategoria}', 'Front\CategoriesController@show');
Route::get('categorias/{slugCategoria}/{slugEstabelecimento}', 'Front\CategoriesController@showEstablishment');

Route::get('calendario/', 'Front\CalendarsController@index');
Route::get('calendario/{slugCalendario}', 'Front\CalendarsController@showCalendar');

Route::get('blogs', 'Front\BlogsController@index');
Route::get('blogs/{slugBlog}', 'Front\BlogsController@show');
Route::get('/depoimentos', 'Front\ReviewController@index');
Route::post('/depoimentos-create', 'Front\ReviewController@store');
Route::get('/contato', 'Front\ContactController@index');

Route::post('/estabelecimentos/busca', 'Front\HomeController@busca');


Route::prefix('services')->namespace('Services')->group(function() {
   Route::post('send-mail', 'MailController@sendContact');
});

Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');

    Route::resource('about', 'Admin\AboutController');
    Route::resource('blogs', 'Admin\BlogsController');
    Route::delete('blogs/{blog}/photos/{photo}', 'Admin\\BlogsController@photoRemove')->name('remove.photo');


    Route::resource('reviews', 'Admin\ReviewsController');
    Route::resource('sliders', 'Admin\SlidersController');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::resource('establishments', 'Admin\EstablishmentsController');
    Route::delete('establishments/{establishment}/photos/{photo}', 'Admin\\EstablishmentsController@photoRemove')->name('remove.photo');

    Route::resource('calendars', 'Admin\CalendarsController');
    Route::delete('calendars/{calendar}/photos/{photo}', 'Admin\\CalendarsController@photoRemove')->name('remove.photo');

    Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    
});

Auth::routes();

app/Models/Calendar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Support\CalendarSupport;

class Calendar extends Model
{
    protected $fillable = [
    	'name',
        'description',
    	'day',
    	'month',
    	'year',
    	'hour',
    	'local',
    	'classification',
    	'slug',
    	'status'
    ];

    //temos alguns modos de trabalho para no poluir nosso valor iniciail
    // digamos que queria carregar ambos os modos em um eloquent, como fazer?

    protected $appends = [
        'abreviado',
        'extenso'
    ];

    public function getAbreviadoAttribute()
    {
        // como no existe na tabela um campo com o nome "abreviado" no temos o suporte igual embaixo,
        // esta conseguindo comprreender? compreendi um pouco.
        return CalendarSupport::abreviado($this->attributes['month'] - 1);
    }

    public function getExtensoAttribute()
    {
        // como no existe na tabela um campo com o nome "abreviado" no temos o suporte igual embaixo,
        // esta conseguindo comprreender? compreendi um pouco.
        return CalendarSupport::extenso($this->attributes['month'] - 1);
    }

    public function scopeEventsInOpened($query) {

        $now = now();

        return $query
                     ->where('day', '>=', $now->day)
                     ->where('month', '>=', $now->month)
                     ->where('year', '>=', $now->year);
    }

    public function photos()
    {
        // o laravel trabalha com pluralidade das models

        // Um blog cotem uma ou mais fotos? mais fotos, ento temos uma relaçao 1:n 1(blog) : n (fotos)
        // quando usar essa relaço um para muitos ou "tem muitos para um" nomeie as tabelas
        // assim: 1 "blog" : n "fotos" = blog_photos como o model possui a pluralidade ele faz a transformaço. Deu para compreender? Deu sim, precisamos mudar isso. Onde foi implementado ambas as models? Isso? aram, s na controller? isso.
        return $this->hasMany('App\Models\CalendarPhoto'); // espero que tenha compreendido,  sim um aprendizado valioso rs
    }
}

app/Http/Controllers/Admin/CalendarsController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\Calendars\StoreRequest;
use App\Http\Requests\Admin\Calendars\UpdateRequest;

use App\Models\Calendar;
use App\Models\CalendarPhoto;

use Image;

class CalendarsController extends Controller
{
    /**
     * Armazena uma nova instancia do model Calendar
     *
     * @var \App\Calendar
     */
    private $calendars;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
      $this->calendars = app(Calendar::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $calendars = Calendar::orderBy($request->input('sort', 'created_at'), 'ASC')->paginate();
      return view('admin.calendars.index', compact('calendars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.calendars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        try {
        app('db')->beginTransaction(); // inicia uma transaçao

        $calendar = Calendar::create($request->all()); // nesse momento o registro ja foi criado.
        
        foreach ($request->photos as $photo) {
          $filename = $photo->store("calendars/{$calendar->id}/photos");
            // associa fotos ao calendar recem criado.
          $calendar->photos()->create(['filename' => $filename]);
        }

        app('db')->commit(); // confirma transaço

        session()->flash('messages.success', ['Calendário cadastrado com sucesso!']);
        return redirect()->route('calendars.index');
      }catch(\Execpetion $error) {
        //
        app('db')->rollback(); // reverte transacao

        session()->flash('messages.error', ['Houve um erro. Tente novamente!']);
        return redirect()->route('calendars.index');
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $calendar = Calendar::findOrFail($id);
      return view('admin.calendars.show', compact('calendar'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $calendar = Calendar::findOrFail($id);
      return view('admin.calendars.edit', compact('calendar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreRequest $request, $id)
    {
      $calendar = $this->calendars->where('id', $id)->first();

      if(!$calendar) {
        session()->flash('messages.error', ['Calendário não existe!']);
        return redirect()->route('calendars.index');
      }

      $calendar->fill($request->all()); // armazena atributos

      $photos = $request->photos; // arquivos

      //
      // Caso exista fotos na ediçao
      //
      if(is_array($photos) && count($photos) > 0) {
        foreach ($photos as $id => $photo) {
          //
          // Verificar se existe foto informada na lista de fotos pertencentes ao calendar.
          //
          if($calendar->photos->contains('id', $id)) {
            //
            // registro atual
            //
            $row = $calendar->photos->find($id);

            $old = $row->filename;

            $row->filename = $photo->store("calendars/{$calendar->id}/photos");

            $row->save(); // atualiza

            if($row->isDirty() && app('filesystem')->exists($old)) {
              app('filesystem')->delete($old);
            }

            continue;
          }
        }
      }

      if($request->hasFile('addPhotos')) {
        //
        // Adicionar novas fotos
        //
        $photos = $request->addPhotos;
      
        foreach ($photos as $file) {
          $filename = $file->store("calendars/{$calendar->id}/photos");
          
          if($filename) {
            //
            // Adicionar foto ao calendar
            //
            $calendar->photos()->create(compact('filename'));

            continue;
          }
        }
      }

      $calendar->save(); // guarda alteraçoes

      session()->flash('messages.success', ['Postagem alterada com sucesso!']);
      return redirect()->route('calendars.index');

  }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Calendar $calendar)
    {

     $db = app('db');

     $db->beginTransaction();

     try {
      $id = $calendar->id;

      $calendar->delete();

      // remover diretorio
      app('filesystem')->delete("calendars/{$id}");

      $db->commit();

      return response(null, 204);
     }catch(\Exception $error) {
       $db->rollback();
       return response()->json(['message' => $error->getMessage()], 400);
     }     
    
    }


  public function photoRemove(Calendar $calendar, $photo_id)
  {
      //
      // verificar se existe relacionamento
      //
      if(!$calendar->photos->contains('id', $photo_id)) abort(403, 'Essa imagem não pertence ao Calendário.');
    
      $photo = $calendar->photos->find($photo_id);

      app('db')->beginTransaction();
      
      try {
        $filename = $photo->filename;

        $photo->delete();

        if(app('filesystem')->exists($filename)) {
          // remover do diretorio
          app('filesystem')->delete($filename);
        }

        app('db')->commit();

        return response(null, 204);
      }catch(\Exception $error) {
        app('db')->rollback();
        return response()->json(['message' => $error->getMessage()], 400);
      }
  }




  }

app/Http/Controllers/Front/CalendarsController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Calendar;

class CalendarsController extends Controller
{
	 /**
     * Armazena uma nova instancia do model Calendar
     *
     * @var \App\Calendar
     */
	 private $calendars;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
    	$this->calendars = app(Calendar::class);
    }

    public function index()
    {
    	return view('front.calendars');
    }

    public function showCalendar(Calendar $calendar)
    {
    	$calendar = Calendar::where('id', $calendar->id)->first();
        $calendar->increment('views');
        return view('front.calendars_show', compact('calendar'));
    }
}

resources/views/admin/calendars/create.blade.php
@extends('admin.base')
@section('title', 'Novo Evento')

@section('content')
<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('calendars.index') }}">Lista de Eventos</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            @yield('title')
          </div>

          <div class="panel-body">

            <form action="{{ route('calendars.store')}}" enctype="multipart/form-data" method="POST">
              <!-- <div class="tabs">
                <ul class="nav nav-tabs">
                  <li class="active">
                    <a href="#description" data-toggle="tab"><i class="fa fa-star"></i> Descrição</a>
                  </li>
                  <li class="">
                    <a href="#images" data-toggle="tab">Imagens</a>
                  </li>
                </ul>
                <div class="tab-content"> -->
                 @component('admin.calendars.form')
                 <!-- <div id="images" class="tab-pane"> -->
                   <div class="row">
                    <div class="col-md-12">
                        <div class="heading-block">
                          <h4>Imagens do Evento</h4>
                        </div>
                      </div>

                    <div class="col-md-12">
                      <input type="file" style="display: none;" name="photos[]" id="input-add-photos" multiple>
                      <button class="btn btn-success" id="add-photos-to-calendar" type="button">
                        <i class="fa fa-plus"></i> Selecionar Imagens
                      </button>
                      <span class="btn disabled" id="display-add-photos">0 selecionados</span>
                    </div>

                    <div class="col-md-12">
                        <span class="help-block">É obrigatório o envio de 1 imagem para Capa do Evento</span>
                        <hr>
                      </div>
                  </div>
                </div><!-- tab-image -->
                @endcomponent
              </div><!-- tab-content -->
            </div><!-- tabs -->
          </form>

        </div><!-- panel-body -->


      </div><!-- panel-default -->
    </div><!-- col-md-12 -->


  </div><!-- row -->
</div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js?1"></script>

<script>
  /* Adicionar arquivos */
  $('#add-photos-to-calendar').click(function(e) {
    e.preventDefault();
    $("#input-add-photos").click();
  });

  $("#input-add-photos").change(function(e) {
    let display = $('span#display-add-photos'),
    files = e.target.files,
    count = files.length;

    if(count > 0) {
      display.empty().html(count + ' selecionados.')
    }else{
      display.empty().html('0 selecionados.')
    }
  });


  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();

  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="name"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="slug"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>
@endsection

resources/views/admin/calendars/edit.blade.php
@extends('admin.base')
@section('title', 'Editar Evento')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $calendar->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('calendars.index') }}">Lista de Eventos</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End calendar Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title') - {{ $calendar->title }}
         </div>

         <div class="panel-body">

          <form action="{{ route('calendars.update', $calendar->id)}}" enctype="multipart/form-data" method="POST">
<!--             <div class="tabs">
              <ul class="nav nav-tabs">
                <li class="active">
                  <a href="#description" data-toggle="tab"><i class="fa fa-star"></i> Descrição</a>
                </li>
                <li class="">
                  <a href="#images" data-toggle="tab">Imagens</a>
                </li>
              </ul>
              <div class="tab-content"> -->

                <input type="hidden" name="_method" value="PUT">
                @component('admin.calendars.form')
                <!-- <div id="images" class="tab-pane"> -->
                <div class="row">
                  <div class="col-md-12">
                        <div class="heading-block">
                          <h4>Imagens do Evento</h4>
                        </div>
                      </div>

                  <div class="col-md-12">
                    <input type="file" style="display: none;" name="addPhotos[]" id="input-add-photos" multiple>
                    <button class="btn btn-success" id="add-photos-to-calendar" type="button">
                      <i class="fa fa-plus"></i> Adicionar Imagens
                    </button>
                    <span class="btn disabled" id="display-add-photos">0 selecionados</span>
                  </div>
                </div>

                <hr>
                @slot('calendar', $calendar)
                <div class="row">
                  @forelse($calendar->photos as $photo)
                  <div id="photo-{{ $photo->id }}" class="col-xs-6 col-sm-4 col-md-3">

                    <div class="panel panel-default">
                      <div class="panel-body">
                        <img id="photo-preview-{{ $photo->id }}" src="{{ asset('storage/' . $photo->filename) }}" alt="{{ $calendar->slug }}" class="img-thumbnail img-responsive" alt="#{{ $photo->id}}">
                      </div>
                      <div class="panel-footer">
                        <div class="btn-group btn-group-xs">
                          <input type="file" name="photos[{{ $photo->id }}]" id="{{ $photo->id }}" class="update-photo" style="display: none;"/>
                          <button class="btn btn-block btn-info" type="button" onclick="document.getElementById({{ $photo->id }}).click()">Alterar </button>
                          <button class="btn btn-block btn-danger" type="button" onclick="remove({{ $calendar->id }}, {{ $photo->id }})">Remover</button>
                        </div>
                      </div>
                    </div>
                  </div>
                  @empty
                  <p>Nao existem fotos para esse calendar.</p>
                  @endforelse
                </div>   

                 <div class="col-md-12">
                    <hr>
                  </div>

              <!-- </div>tab-images -->
              @endcomponent
         <!--    </div>!-- tab-content --
          </div>-- tabs -- -->
            </form>

          </div><!-- panel-body -->


        </div><!-- panel-default -->
      </div><!-- col-md-12 -->


    </div><!-- row -->
  </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js?1"></script>

<script>

  function remove(calendar, photo) {
    let doc = $('#photo-' + photo);
    let request = $.ajax({
     url: '/dashboard/calendars/' + calendar + '/photos/' + photo,
     type: 'DELETE',
     statusCode: {
       204: function() {
            doc.fadeOut(); // ocultar registro
          }
        }
      })
  }

  /* Gerar Previa */
  $('.update-photo').change(function(e) {
    console.log('updated.')
    const ref = e.target;

    if(!ref.files) return;

    let id = ref.id,
    image = $('#photo-preview-' + id),
    file = ref.files[0],
    old = image.attr('src')

    var reader = new FileReader();

    reader.onload = function(event) {

      image.css({filter: blur(1.5)})

      image.fadeOut(500, function() {
        image.attr('src', event.target.result);
        image.fadeIn(200, function() {
          image.css({filter: blur(0)})
        });
      })
    }
      //
      reader.readAsDataURL(file);
    });

  /* Adicionar arquivos */
  $('#add-photos-to-calendar').click(function(e) {
    e.preventDefault();
    $("#input-add-photos").click();
  });

  $("#input-add-photos").change(function(e) {
    let display = $('span#display-add-photos'),
    files = e.target.files,
    count = files.length;

    if(count > 0) {
      display.empty().html(count + ' selecionados.')
    }else{
      display.empty().html('0 selecionados.')
    }
  });


  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();

  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="title"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="slug"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>
@endsection

resources/views/admin/calendars/show.blade.php
@extends('admin.base')
@section('title', 'Detalhes do Evento')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $calendar->name }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('calendars.index') }}">Lista de Eventos</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End calendar Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            <h2>{{ $calendar->name }}</h2>
            <h4>{{ $calendar->day }}/{{ $calendar->month }} às {{ $calendar->hour }}</h4>
          </div>

          <div class="panel-body">

            <img src="/storage/{{ $calendar->image }}" alt="Calendário" class="img-thumbnail">

            <p><small>Criado em {{ $calendar->created_at->format('d/m/Y H:i:s') }} | Atualizado em {{ $calendar->updated_at->format('d/m/Y H:i:s') }}</small></p>
            <blockquote>
              Endereço: {{ $calendar->local }}
              <br>
              Classificação: {{ $calendar->classification }}
              <br>
              {!! $calendar->description !!}</blockquote>

            <hr>

            <a href="{{ route('calendars.index') }}" class="btn btn-xs btn-warning">Voltar</a>
            <a href="{{ route('calendars.edit', $calendar->id) }}" class="btn btn-xs btn-primary">Editar</a>
            <a href="{{ route('calendars.destroy', $calendar->id) }}" class="btn btn-xs btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form-calendars').submit();"><i class="fa fa-remove"></i> Deletar</a></li>
            <form id="delete-form-calendars" action="{{ route('calendars.destroy', $calendar->id) }}" method="POST" style="display: none;">
             {!! csrf_field() !!}
             <input type="hidden" name="_method" value="DELETE">
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
@endsection