routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('http://webmail.innsystem.com.br/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });

Route::get('/manutencao', 'Front\HomeController@maintence');
Route::get('/', 'Front\HomeController@suspenso');

Route::get('/sobre', 'Front\AboutController@index');

Route::get('categorias', 'Front\CategoriesController@index');
Route::get('categorias/{slugCategoria}', 'Front\CategoriesController@show');
Route::get('categorias/{slugCategoria}/{slugEstabelecimento}', 'Front\CategoriesController@showEstablishment');

Route::get('calendario/', 'Front\CalendarsController@index');
Route::get('calendario/{slugCalendario}', 'Front\CalendarsController@showCalendar');

Route::get('blogs', 'Front\BlogsController@index');
Route::get('blogs/{slugBlog}', 'Front\BlogsController@show');
Route::get('/depoimentos', 'Front\ReviewController@index');
Route::post('/depoimentos-create', 'Front\ReviewController@store');
Route::get('/contato', 'Front\ContactController@index');

Route::post('/estabelecimentos/busca', 'Front\HomeController@busca');


Route::prefix('services')->namespace('Services')->group(function() {
   Route::post('send-mail', 'MailController@sendContact');
});

Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');

    Route::resource('about', 'Admin\AboutController');
    Route::resource('blogs', 'Admin\BlogsController');
    Route::delete('blogs/{blog}/photos/{photo}', 'Admin\\BlogsController@photoRemove')->name('remove.photo');


    Route::resource('reviews', 'Admin\ReviewsController');
    Route::resource('sliders', 'Admin\SlidersController');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::resource('establishments', 'Admin\EstablishmentsController');
    Route::delete('establishments/{establishment}/photos/{photo}', 'Admin\\EstablishmentsController@photoRemove')->name('remove.photo');

    Route::resource('calendars', 'Admin\CalendarsController');
    Route::delete('calendars/{calendar}/photos/{photo}', 'Admin\\CalendarsController@photoRemove')->name('remove.photo');

    Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    
});

Auth::routes();

app/Models/Establishment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Establishment extends Model
{
    protected $fillable = [
        'name',
        'proprietary',
        'category_id',
        'description',
        'image',
        'cep',
        'address',
        'number',
        'distric',
        'city',
        'state',
        'country',
        'phone',
        'phone_whatsapp',
        'cellphone',
        'email',
        'website',
        'slug',
        'status'
    ];

    public function getPostCategory(){
        return Category::where('id', $this->category_id)->first()->title;
    }
    public function getPostCategorySlug(){
        return Category::where('id', $this->category_id)->first()->slug;
    }

    public function photos()
    {
        // o laravel trabalha com pluralidade das models

        // Um blog cotem uma ou mais fotos? mais fotos, ento temos uma relaçao 1:n 1(blog) : n (fotos)
        // quando usar essa relaço um para muitos ou "tem muitos para um" nomeie as tabelas
        // assim: 1 "blog" : n "fotos" = blog_photos como o model possui a pluralidade ele faz a transformaço. Deu para compreender? Deu sim, precisamos mudar isso. Onde foi implementado ambas as models? Isso? aram, s na controller? isso.
        return $this->hasMany('App\Models\EstablishmentPhoto'); // espero que tenha compreendido,  sim um aprendizado valioso rs
    }
}

app/Http/Controllers/Admin/EstablishmentsController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\Establishments\StoreRequest;
use App\Http\Requests\Admin\Establishments\UpdateRequest;

use App\Models\Establishment;
use App\Models\EstablishmentPhoto;

use Image;
use App\Support\UploadSupport;

class EstablishmentsController extends Controller
{
    /**
     * Armazena uma nova instancia do model Establishment
     *
     * @var \App\Establishment
     */
    private $establishments;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
      $this->establishments = app(Establishment::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $establishments = Establishment::orderBy($request->input('sort', 'created_at'), 'ASC')->paginate();
      return view('admin.establishments.index', compact('establishments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.establishments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
      try {
        app('db')->beginTransaction(); // inicia uma transaçao
  
        $data = $request->all();
  
        if (isset($data['phone_whatsapp'])) {
          $data['phone_whatsapp'] = 1;
        } else {
          $data['phone_whatsapp'] = 0;
        }
  
        $establishment = Establishment::create($data); // nesse momento o registro ja foi criado.
  
        foreach ($request->photos as $photo) {
          // dd($photo);
          $filename = $photo->store("establishments/{$establishment->id}/photos");
          // associa fotos ao establishment recem criado.
          $establishment->photos()->create(['filename' => $filename]);
        }
  
        app('db')->commit(); // confirma transaço
  
        session()->flash('messages.success', ['Estabelecimento cadastrado com sucesso!']);
        return redirect()->route('establishments.index');
      } catch (\Execpetion $error) {
        //
        app('db')->rollback(); // reverte transacao
  
        session()->flash('messages.error', ['Houve um erro. Tente novamente!']);
        return redirect()->route('establishments.index');
      }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $establishment = Establishment::findOrFail($id);
      return view('admin.establishments.show', compact('establishment'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $establishment = Establishment::findOrFail($id);
      return view('admin.establishments.edit', compact('establishment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreRequest $request, $id)
    {
      $establishment = $this->establishments->where('id', $id)->first();

      if(!$establishment) {
        session()->flash('messages.error', ['Establecimento não existe!']);
        return redirect()->route('establishments.index');
      }

      $data = $request->all();

      if (isset($data['phone_whatsapp'])) {
        $data['phone_whatsapp'] = 1;
      } else {
        $data['phone_whatsapp'] = 0;
      }

      $establishment->fill($data); // armazena atributos

      $photos = $request->photos; // arquivos

      //
      // Caso exista fotos na ediçao
      //
      if(is_array($photos) && count($photos) > 0) {
        foreach ($photos as $id => $photo) {
          //
          // Verificar se existe foto informada na lista de fotos pertencentes ao establishment.
          //
          if($establishment->photos->contains('id', $id)) {
            //
            // registro atual
            //
            $row = $establishment->photos->find($id);

            $old = $row->filename;

            $row->filename = $photo->store("establishments/{$establishment->id}/photos");

            $row->save(); // atualiza

            if($row->isDirty() && app('filesystem')->exists($old)) {
              app('filesystem')->delete($old);
            }

            continue;
          }
        }
      }

      if($request->hasFile('addPhotos')) {
        //
        // Adicionar novas fotos
        //
        $photos = $request->addPhotos;

        foreach ($photos as $file) {
          $filename = $file->store("establishments/{$establishment->id}/photos");
          
          if($filename) {
            //
            // Adicionar foto ao establishment
            //
            $establishment->photos()->create(compact('filename'));

            continue;
          }
        }
      }

      $establishment->save(); // guarda alteraçoes

      session()->flash('messages.success', ['Establecimento alterado com sucesso!']);
      return redirect()->route('establishments.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Establishment $establishment)
    {

     $db = app('db');

     $db->beginTransaction();

     try {
      $id = $establishment->id;

      $establishment->delete();

      // remover diretorio
      app('filesystem')->delete("establishments/{$id}");

      $db->commit();

      return response(null, 204);
    }catch(\Exception $error) {
     $db->rollback();
     return response()->json(['message' => $error->getMessage()], 400);
   }
 }



 public function photoRemove(Establishment $establishment, $photo_id)
 {
      //
      // verificar se existe relacionamento
      //
  if(!$establishment->photos->contains('id', $photo_id)) abort(403, 'Essa imagem não pertence ao Estabelecimento.');

  $photo = $establishment->photos->find($photo_id);

  app('db')->beginTransaction();

  try {
    $filename = $photo->filename;

    $photo->delete();

    if(app('filesystem')->exists($filename)) {
          // remover do diretorio
      app('filesystem')->delete($filename);
    }

    app('db')->commit();

    return response(null, 204);
  }catch(\Exception $error) {
    app('db')->rollback();
    return response()->json(['message' => $error->getMessage()], 400);
  }
}


}

resources/views/admin/establishments/create.blade.php
@extends('admin.base')
@section('title', 'Novo Estabelecimento')

@section('content')
<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('establishments.index') }}">Página de Estabelecimentos</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            @yield('title')
          </div>

          <div class="panel-body">

            <form action="{{ route('establishments.store')}}" enctype="multipart/form-data" method="POST">
              <!--
              <div class="tabs">
                <ul class="nav nav-tabs">
                  <li class="active">
                    <a href="#description" data-toggle="tab"><i class="fa fa-star"></i> Descrição</a>
                  </li>
                  <li class="">
                    <a href="#images" data-toggle="tab">Imagens</a>
                  </li>
                </ul>
                <div class="tab-content">
                -->
                  @component('admin.establishments.form')
                  <!-- <div id="images" class="tab-pane"> -->
                    <div class="row">
                      <div class="col-md-12">
                        <div class="heading-block">
                          <h4>Imagens do Estabelecimento</h4>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <input type="file" style="display: none;" name="photos[]" id="input-add-photos" accept="image/jpg, image/jpeg, image/png" multiple>
                        <button class="btn btn-success" id="add-photos-to-establishment" type="button">
                          <i class="fa fa-plus"></i> Selecionar Imagens
                        </button>
                        <span class="btn disabled" id="display-add-photos">0 selecionados</span>
                      </div>

                      <div class="col-md-12">
                        <span class="help-block">É obrigatório o envio de 1 imagem para Capa do Estabelecimento</span>
                        <hr>
                      </div>
                    </div>
                  </div>
                  @endcomponent
             <!--    </div>tab-content
                           </div>tabs -->
            </form>

          </div><!-- panel-body -->


        </div><!-- panel-default -->
      </div><!-- col-md-12 -->


    </div><!-- row -->
  </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
<link href="{{ asset('front/js/summernote/summernote.css?13') }}" rel="stylesheet">
<link href="{{ asset('front/js/summernote/summernote-bs4.css?13') }}" rel="stylesheet">
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<script type="text/javascript" src="/front/js/summernote/summernote.js?2"></script>
<script type="text/javascript" src="/front/js/summernote/lang/summernote-pt-BR.js?2"></script>

<script type="text/javascript">
  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote({
      lang: 'pt-BR'
    });
    $('button[data-event="showImageDialog"], button[data-event="showVideoDialog"], button[data-event="codeview"], .note-toolbar .note-table').hide();
  });
</script>

<script>

  /* Adicionar arquivos */
  $('#add-photos-to-establishment').click(function(e) {
    e.preventDefault();
    $("#input-add-photos").click();
  });

  $("#input-add-photos").change(function(e) {
    let display = $('span#display-add-photos'),
    files = e.target.files,
    count = files.length;

    if(count > 0) {
      display.empty().html(count + ' selecionados.')
    }else{
      display.empty().html('0 selecionados.')
    }
  });

  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="name"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="slug"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>
@endsection

resources/views/admin/establishments/edit.blade.php
@extends('admin.base')
@section('title', 'Editar Estabelecimento')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $establishment->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('establishments.index') }}">Página de Estabelecimento</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End establishment Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title') - {{ $establishment->title }}
         </div>

         <div class="panel-body">

          <form action="{{ route('establishments.update', $establishment->id)}}" enctype="multipart/form-data" method="POST">
<!--             <div class="tabs">
              <ul class="nav nav-tabs">
                <li class="active">
                  <a href="#description" data-toggle="tab"><i class="fa fa-star"></i> Descrição</a>
                </li>
                <li class="">
                  <a href="#images" data-toggle="tab">Imagens</a>
                </li>
              </ul>
              <div class="tab-content"> -->

                <input type="hidden" name="_method" value="PUT">
                @component('admin.establishments.form')
              <!--   <div id="images" class="tab-pane"> -->
                  <div class="row">
                    
                    <div class="col-md-12">
                        <div class="heading-block">
                          <h4>Imagens do Estabelecimento</h4>
                        </div>
                      </div>

                    <div class="col-md-12">
                      <input type="file" style="display: none;" name="addPhotos[]" id="input-add-photos" accept="image/jpg, image/jpeg, image/png" multiple>
                      <button class="btn btn-success" id="add-photos-to-establishment" type="button">
                        <i class="fa fa-plus"></i> Adicionar Imagens
                      </button>
                      <span class="btn disabled" id="display-add-photos">0 selecionados</span>
                    </div>
                  </div>

                  <hr>

                  @slot('establishment', $establishment)
                  <div class="row">
                    @forelse($establishment->photos as $photo)
                    <div id="photo-{{ $photo->id }}" class="col-xs-6 col-sm-4 col-md-3">

                      <div class="panel panel-default">
                        <div class="panel-heading">
                        <div class="panel-body">
                          <img id="photo-preview-{{ $photo->id }}" src="{{ asset('storage/' . $photo->filename) }}" alt="{{ $establishment->slug }}" class="img-thumbnail img-responsive" alt="#{{ $photo->id}}">
                        </div><!-- panel-body -->

                        <div class="panel-footer">
                          <div class="btn-group btn-group-xs">
                            <input type="file" name="photos[{{ $photo->id }}]" id="{{ $photo->id }}" class="update-photo" style="display: none;"/>
                            <button class="btn btn-block btn-info" type="button" onclick="document.getElementById({{ $photo->id }}).click()">Alterar imagem</button>
                            <button class="btn btn-block btn-danger" type="button" onclick="remove({{ $establishment->id }}, {{ $photo->id }})">Remover</button>
                          </div><!-- btn-group -->
                        </div><!-- panel-footer -->
                      </div><!-- panel-heading -->
                    </div><!-- panel -->

                  </div>

                    @empty
                    <p>Nao existem fotos para esse establishment.</p>
                    @endforelse
                  </div>

                  <div class="col-md-12">
                    <hr>
                  </div>
                  
               <!--  </div>tab-images -->
                @endcomponent
              </form>

            </div><!-- panel-body -->


          </div><!-- panel-default -->
        </div><!-- col-md-12 -->


      </div><!-- row -->
    </div><!-- container-padding -->

  </div><!-- container-default -->
  <!-- END CONTAINER -->
  @endsection

  @section('cssPage')
  <link href="{{ asset('front/js/summernote/summernote.css?13') }}" rel="stylesheet">
<link href="{{ asset('front/js/summernote/summernote-bs4.css?13') }}" rel="stylesheet">
  @endsection

  @section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<script type="text/javascript" src="/front/js/summernote/summernote.js?2"></script>
<script type="text/javascript" src="/front/js/summernote/lang/summernote-pt-BR.js?2"></script>

<script type="text/javascript">
  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote({
      lang: 'pt-BR'
    });
    $('button[data-event="showImageDialog"], button[data-event="showVideoDialog"], button[data-event="codeview"], .note-toolbar .note-table').hide();
  });
</script>

<script>
  function remove(establishment, photo) {
    let doc = $('#photo-' + photo);
    let request = $.ajax({
      url: '/dashboard/establishments/' + establishment + '/photos/' + photo,
      type: 'DELETE',
      statusCode: {
        204: function() {
          doc.fadeOut(); // ocultar registro
        }
      }
    })
  }

  /* Gerar Previa */
  $('.update-photo').change(function(e) {
    console.log('updated.')
    const ref = e.target;

    if (!ref.files) return;

    let id = ref.id,
      image = $('#photo-preview-' + id),
      file = ref.files[0],
      old = image.attr('src')

    var reader = new FileReader();

    reader.onload = function(event) {

      image.css({
        filter: blur(1.5)
      })

      image.fadeOut(500, function() {
        image.attr('src', event.target.result);
        image.fadeIn(200, function() {
          image.css({
            filter: blur(0)
          })
        });
      })
    }
    //
    reader.readAsDataURL(file);
  });

  /* Adicionar arquivos */
  $('#add-photos-to-establishment').click(function(e) {
    e.preventDefault();
    $("#input-add-photos").click();
  });

  $("#input-add-photos").change(function(e) {
    let display = $('span#display-add-photos'),
      files = e.target.files,
      count = files.length;

    if (count > 0) {
      display.empty().html(count + ' selecionados.')
    } else {
      display.empty().html('0 selecionados.')
    }
  });

  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="title"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="slug"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>
@endsection

resources/views/admin/establishments/show.blade.php
@extends('admin.base')
@section('title', 'Detalhes do Estabelecimento')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $establishment->name }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('establishments.index') }}">Página de Estabelecimentos</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End establishment Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            <h2>{{ $establishment->name }}</h2>
            <h4>{{ $establishment->getPostCategory() }}</h4>
          </div>

          <div class="panel-body">

            <img src="/storage/{{ $establishment->image }}" alt="Calendário" class="img-thumbnail">

            <p><small>Criado em {{ $establishment->created_at->format('d/m/Y H:i:s') }} | Atualizado em {{ $establishment->updated_at->format('d/m/Y H:i:s') }}</small></p>

            <blockquote>
              <p><b>Localização</b></p>
              <ul>
                <li>Proprietário: {{ $establishment->proprietary }}</li>
                <li>CEP: {{ $establishment->cep }}</li>
                <li>Endereço: {{ $establishment->address }}, N° {{ $establishment->number }}</li>
                <li>Bairro: {{ $establishment->distric }}</li>
                <li>Cidade: {{ $establishment->city }}</li>
                <li>Estado: {{ $establishment->state }}</li>
                <li>Telefone: {{ $establishment->phone }}</li>
                @if($establishment->cellphone)
                  <li>Celular: {{ $establishment->cellphone }}</li>
                @endif

                <li>Status: <span class="label label-{{ ($establishment->status == '1' ? 'success' : 'danger' ) }}">
                      {{ ($establishment->status == '1' ? 'Habilitado' : 'Desabilitado' ) }}
                    </span></li>
              </ul>
            </blockquote>

            @if($establishment->description)
            <blockquote>
              {{ $establishment->description }}
            </blockquote>
            @endif

            <hr>

            <a href="{{ route('establishments.index') }}" class="btn btn-xs btn-warning">Voltar</a>
            <a href="{{ route('establishments.edit', $establishment->id) }}" class="btn btn-xs btn-primary">Editar</a>
            <a href="{{ route('establishments.destroy', $establishment->id) }}" class="btn btn-xs btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form-establishments').submit();"><i class="fa fa-remove"></i> Deletar</a></li>
            <form id="delete-form-establishments" action="{{ route('establishments.destroy', $establishment->id) }}" method="POST" style="display: none;">
             {!! csrf_field() !!}
             <input type="hidden" name="_method" value="DELETE">
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
@endsection